apiVersion: v1
data:
  traefik.tom: |
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
          `entryPoints`.`https`.`tls`.`certificates`
          CertFile = "/ssl/ca.pem"
          KeyFile = "/ssl/ca-key.pem"
kind: ConfigMap
metadata: 
  name: traefik-conf
  namespace: kube-system 
