apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: server
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      hostNetwork: false
      containers:
      - image: 10.39.101.226:5000/mongo
        name: mongodb
        args: ["--auth"]
        ports:
        - containerPort: 27017 
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data
      volumes:
        - name: mongodb-data
          hostPath:
            path: /K8s-Deployment/mongodb/db-data
      nodeSelector:
        nodeName: caocentos7  
        