apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: nginx
      image: 10.39.101.226:5000/nginx
      ports:
        - containerPort: 3000
          name: p3000
          hostPort: 3000     
          
        - containerPort: 5601
          name: p5601
          hostPort: 5601
               
        - containerPort: 9200
          name: p9200
          hostPort: 9200
                            
        - containerPort: 9300
          name: p9300
          hostPort: 9300                  

               
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
  volumes:
    - name: nginx-conf
      hostPath:
        path: /K8s-Deployment/nginx/nginx.conf
  nodeSelector:
    nodeName: caocentos7
