apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: server 
spec:
  type: LoadBalancer
  ports:
  - port: 8008
    targetPort: 8008
    nodePort: 30008
  selector:
    app: nginx 

---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      nodeSelector:
        nodeName: caocentos7
      containers:
      - image: 10.39.101.226:5000/nginx
        name: nginx
        ports:
        - containerPort: 8008
          hostPort: 8008
