---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: filebeat
  namespace: elk 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      name: filebeat
      labels:
        app: filebeat
    spec:
      hostNetwork: false
      volumes:
        - name: config
          configMap:
            name: filebeat-configmap
      containers:
      - image: prima/filebeat 
        name: filebeat
        volumeMounts:
          - mountPath: "/config"
            name: "config"
        command: [ "/bin/sh", "-c", "cp -f /config/filebeat.conf.yml /filebeat.yml" ]
        

     