filebeat.prospectors:
  - type: log
    paths:
      - /var/log/*.log
    fields:
      level: debug
      review: 1
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

