---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: elk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      name: logstash
      labels:
        app: logstash
    spec:
      hostNetwork: false
      containers:
      - image: 10.39.101.226:5000/logstash 
        name: logstash
        ports:
        - containerPort: 9600
        command: ["-f", "/config-dir/logstash.conf"]             
        volumeMounts:
          - mountPath: /config-dir
            name: logstash-conf
      volumes:
        - name: logstash-conf
          hostPath:
            path: /K8s-Deployment/elk
      nodeSelector:
        nodeName: caocentos7  

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  type: LoadBalancer
  ports:
  - port: 9600
    targetPort: 9600
 
  selector:
    app: logstash
    
---
 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logstash
  namespace: elk
spec:
  rules:
  - host: logstash.cs.cloud.com
    http:
      paths:
        - backend:
            serviceName: "logstash"
            servicePort: 9600        
        

     