apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  volumes:
    - name: config
      configMap:
        name: busybox-config
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - mountPath: "/config"
        name: "config"
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet